# -*- coding: utf-8 -*-
"""workshop1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nIk0E0UDcWoRfSWOV_gwT4o-Oc4cYo5C
"""

first_name = input("Please Enter Your First Name: ")
print(first_name)

"""Here we are asking user to enter a value and checks if its negative, non-negative or positive
by the control structure"""
value = int(input("Please Enter a Number: ")) #input keyword always takes any value as a string. Thus, we use int() function
#it is called casting. It converts a value to different data types
if value < 0:
 print('The number is negative')
elif value == 0:
 print('The number is non-negative')
else:
 print('The number is positive')

total = 0
counter = 1
while counter <= 10: #stopping condition
 total = total + counter #sum
 counter += 1 #increament
print(total)

total = 0
for counter in range(1, 11, 1): #initialize, stopping condition, increament.
 total = total+ counter
print(total)

"""A list can be created using a comma-separated sequence within square brackets"""
first_list = [1, 2, 3, 8]

"""In a list, the individual items can be accessed by subscript/index:"""
print("First value of the list is ", first_list[0])
print("Last value of the list is ", first_list[-1])

"""The elements of a list can also be accessed by traversing the list using the iterator mechanism:"""
for values in first_list:
 print(values)

#append
first_list.append(10)
print("After adding another element in the list, the list is ", first_list)
#modify
first_list[2] = 5
print("After modifying an element in the list, the list is ", first_list)
#insert: elements can be inserted in any positon/index
first_list.insert(2, 12)
print("After inserting an element in the list in the third position, the list is ", first_list)

"""There are lot of ways to access elements of the dictionary. However, we will parctice the most common one.
The traversal using the iterator mechanism (for statement) is made over the keys in a dictionary"""
zipCode = {'London':290, 'Leeds':578, 'Wolverhampton':911}
for key in zipCode:
 print(key, '= ', zipCode[key])

"""To explicitely find the list of keys or list value we can use the following"""
key_list = zipCode.keys()
value_list = zipCode.values()
print(key_list)
print(value_list)

"""To change the value of a corresponding key we can do the following"""
zipCode['London'] = 666
for key in zipCode:
 print(key, '= ', zipCode[key])

"""Using the same technique we can add another entry. However, the key must be unique.
Duplicate key name will modify the value only"""
zipCode['Birmingham'] = 111
for key in zipCode:
 print(key, '= ', zipCode[key])

def oddEven(num):
    if num % 2 == 0:
        print("The number is even")
    else:
        print("The number is odd")
    return

num = int(input("Please Enter a Number: "))
oddEven(num)

#Display Fibonacci Series (10 Terms)
n = 10
a = 0
b = 1

print("Fibonacci Series:")

for i in range(n):
    print(a)
    c = a + b
    a = b
    b = c

#Factorial of a Number (User Input)
num = int(input("Enter a number: "))
factorial = 1

for i in range(1, num + 1):
    factorial = factorial * i

print("Factorial of", num, "is", factorial)

#Right Angle Triangle using For Loop
rows = 5

for i in range(1, rows + 1):
    for j in range(i):
        print("*", end=" ")
    print()

#Simple Calculator using Functions
def add(a, b):
    return a + b

def subtract(a, b):
    return a - b

def multiply(a, b):
    return a * b

def divide(a, b):
    return a / b

num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))

print("Addition:", add(num1, num2))
print("Subtraction:", subtract(num1, num2))
print("Multiplication:", multiply(num1, num2))
print("Division:", divide(num1, num2))

#Remove First Duplicate Element of List
my_list = [1, 2, 3, 2, 4, 5]

seen = []

for item in my_list:
    if item not in seen:
        seen.append(item)

print(seen)

#Extract Keys from Dictionary
sample_dict = {
    "name": "Anderson",
    "age": 35,
    "salary": 5000,
    "city": "London"
}

keys = ["name", "salary"]

new_dict = {}

for key in keys:
    new_dict[key] = sample_dict[key]

print(new_dict)

#Convert Two Lists into Dictionary
list_one = ['one', 'two', 'three']
list_two = [1, 2, 3]

result = dict(zip(list_one, list_two))

print(result)